/* Action types */
export const actionTypes = {
  SCHEDULE_FETCH: 'SCHEDULE/FETCH',
  SCHEDULE_FETCH_SUCCESS: 'SCHEDULE/FETCH_SUCCESS',
  SCHEDULE_FETCH_ERROR: 'SCHEDULE/FETCH_ERROR',
  SCHEDULE_DATE_UPDATE: 'SCHEDULE/DATE_UPDATE',
  SCHEDULE_SET_CURRENT: 'SCHEDULE/SET_CURRENT',
  SCHEDULE_SAVE_CURRENT: 'SCHEDULE/SAVE_CURRENT'
};
